DROP TABLE ACC_CONSUMPTION;
DROP TABLE ACC_ACCOUNT;
DROP TABLE ACC_CONSUMPTION_PATTERNS;
DROP TABLE ACC_CONSUMPTION_TYPE_DETAIL;
DROP TABLE ACC_CONSUMPTION_TYPE;

CREATE TABLE ACC_CONSUMPTION_TYPE(
	SEQ INT IDENTITY NOT NULL PRIMARY KEY,
	TYPE_NAME VARCHAR(30),
	VERSION INT,
	CREATE_DATE DATETIME,
	CREATE_USER VARCHAR(20),
	MODIFY_DATE DATETIME,
	MODIFY_USER VARCHAR(20)
);

CREATE TABLE ACC_CONSUMPTION_TYPE_DETAIL(
	SEQ INT IDENTITY NOT NULL PRIMARY KEY,
	TYPE_SEQ INT REFERENCES ACC_CONSUMPTION_TYPE (SEQ),
	TYPE_DETAIL_NAME VARCHAR(30),
	VERSION INT,
	CREATE_DATE DATETIME,
	CREATE_USER VARCHAR(20),
	MODIFY_DATE DATETIME,
	MODIFY_USER VARCHAR(20)
);

CREATE TABLE ACC_CONSUMPTION_PATTERNS (
	SEQ INT IDENTITY NOT NULL PRIMARY KEY,
	PATTERN_NAME VARCHAR(30),
	VERSION INT,
	CREATE_DATE DATETIME,
	CREATE_USER VARCHAR(20),
	MODIFY_DATE DATETIME,
	MODIFY_USER VARCHAR(20)
);

CREATE TABLE ACC_ACCOUNT (
	SEQ INT IDENTITY NOT NULL PRIMARY KEY,
	ACCOUNT_BANK VARCHAR(50),
	ACCOUNT_BALANCE INT,
	VERSION INT,
	CREATE_DATE DATETIME,
	CREATE_USER VARCHAR(20),
	MODIFY_DATE DATETIME,
	MODIFY_USER VARCHAR(20)
);

CREATE TABLE ACC_CONSUMPTION (
	SEQ INT IDENTITY NOT NULL PRIMARY KEY,
	ACCOUNT_SEQ INT REFERENCES ACC_ACCOUNT (SEQ),
	CONSUMPTION_NAME INT,
	TYPE_SEQ INT REFERENCES ACC_CONSUMPTION_TYPE (SEQ),
	DETAIL_SEQ INT REFERENCES ACC_CONSUMPTION_TYPE_DETAIL (SEQ),
	PATTERNS_SEQ INT REFERENCES ACC_CONSUMPTION_PATTERNS (SEQ),
	CONSUMPTION_AMOUNT INT,
	VERSION INT,
	CREATE_DATE DATETIME,
	CREATE_USER VARCHAR(20),
	MODIFY_DATE DATETIME,
	MODIFY_USER VARCHAR(20)
);